export const testNarratorsData = [
  {
    id: 1,
    name: 'Diego Soto',
    city: 'Santiago',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 2,
    name: 'Valentina Rodríguez',
    city: 'Valparaíso',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 3,
    name: 'Javier Torres',
    city: 'Concepción',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 4,
    name: 'Florencia Gómez',
    city: 'La Serena',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 5,
    name: 'Matías Pérez',
    city: 'Arica',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 6,
    name: 'Isabel Muñoz',
    city: 'Antofagasta',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 7,
    name: 'Gabriel Silva',
    city: 'Temuco',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 8,
    name: 'Constanza Morales',
    city: 'Valdivia',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 9,
    name: 'Felipe Ortiz',
    city: 'Iquique',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 10,
    name: 'Daniela Vargas',
    city: 'Punta Arenas',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 11,
    name: 'Rocío González',
    city: 'Valparaíso',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 12,
    name: 'Sebastián Castro',
    city: 'Concepción',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 13,
    name: 'Francisca Herrera',
    city: 'La Serena',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 14,
    name: 'Carlos Torres',
    city: 'Arica',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 15,
    name: 'María Flores',
    city: 'Antofagasta',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 16,
    name: 'Ignacio Pérez',
    city: 'Temuco',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 17,
    name: 'Valeria Sánchez',
    city: 'Valdivia',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 18,
    name: 'Eduardo Gómez',
    city: 'Iquique',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 19,
    name: 'Camila Muñoz',
    city: 'Punta Arenas',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 20,
    name: 'Nicolás Silva',
    city: 'Santiago',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 21,
    name: 'Isabella Ramírez',
    city: 'Valparaíso',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 22,
    name: 'Tomás Ortiz',
    city: 'Concepción',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 23,
    name: 'Antonia Vargas',
    city: 'La Serena',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 24,
    name: 'Felipe González',
    city: 'Arica',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 25,
    name: 'Daniela Castro',
    city: 'Antofagasta',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 26,
    name: 'Gabriel Torres',
    city: 'Temuco',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 27,
    name: 'Javiera Muñoz',
    city: 'Valdivia',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 28,
    name: 'Matías Soto',
    city: 'Iquique',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 29,
    name: 'Camila Flores',
    city: 'Punta Arenas',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 30,
    name: 'Martín Gómez',
    city: 'Santiago',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 31,
    name: 'Valentina Herrera',
    city: 'Valparaíso',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 32,
    name: 'Sebastián Ramírez',
    city: 'Concepción',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 33,
    name: 'Antonia Sánchez',
    city: 'La Serena',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 34,
    name: 'Felipe Vargas',
    city: 'Arica',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 35,
    name: 'Daniela Torres',
    city: 'Antofagasta',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 36,
    name: 'Matías Muñoz',
    city: 'Temuco',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 37,
    name: 'Javiera Castro',
    city: 'Valdivia',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 38,
    name: 'Martín Soto',
    city: 'Iquique',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 39,
    name: 'Camila Flores',
    city: 'Punta Arenas',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 40,
    name: 'Francisco Gómez',
    city: 'Santiago',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 41,
    name: 'Isabella Ramírez',
    city: 'Valparaíso',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 42,
    name: 'Tomás Ortiz',
    city: 'Concepción',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 43,
    name: 'Antonia Vargas',
    city: 'La Serena',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 44,
    name: 'Felipe González',
    city: 'Arica',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 45,
    name: 'Daniela Castro',
    city: 'Antofagasta',
    speciality: 'Prevención de Riesgos Químicos',
  },
  {
    id: 46,
    name: 'Gabriel Torres',
    city: 'Temuco',
    speciality: 'Prevención de Riesgos Eléctricos',
  },
  {
    id: 47,
    name: 'Javiera Muñoz',
    city: 'Valdivia',
    speciality: 'Trabajo en Alturas',
  },
  {
    id: 48,
    name: 'Matías Soto',
    city: 'Iquique',
    speciality: 'Trabajo en Espacios Confinados',
  },
  {
    id: 49,
    name: 'Camila Flores',
    city: 'Punta Arenas',
    speciality: 'Prevención de Riesgos Ergonómicos',
  },
  {
    id: 50,
    name: 'Martín Gómez',
    city: 'Santiago',
    speciality: 'Prevención de Riesgos Químicos',
  },
];

export const testBookingData = [
  {
    id: 1,
    userName: 'Usuario 1',
    locutorName: 'Locutor 1',
    specialty: 'Trabajo en Alturas',
    city: 'Santiago',
    date: '2024-01-15'
  },
  {
    id: 2,
    userName: 'Usuario 2',
    locutorName: 'Locutor 3',
    specialty: 'Trabajo en Espacios Confinados',
    city: 'Viña del mar',
    date: '2024-01-17'
  },
  {
    id: 3,
    userName: 'Usuario 1',
    locutorName: 'Locutor 1',
    specialty: 'Trabajo en Alturas',
    city: 'Santiago',
    date: '2024-01-17'
  },
  {
    id: 4,
    userName: 'Usuario 1',
    locutorName: 'Locutor 1',
    specialty: 'Trabajo en Alturas',
    city: 'Concepción',
    date: '2024-02-22'
  },
];

export const citiesData = [
  'Santiago',
  'Valparaíso',
  'Concepción',
  'La Serena',
  'Arica',
  'Antofagasta',
  'Temuco',
  'Valdivia',
  'Iquique',
  'Punta Arenas',
];

export const specialtiesData = [
  'Trabajo en Alturas',
  'Trabajo en Espacios Confinados',
  'Prevención de Riesgos Químicos',
  'Prevención de Riesgos Eléctricos',
  'Prevención de Riesgos Ergonómicos',
];
